VERSION = "1.0"
WIN_RESIZABLE = False
WIN_WIDTH = 416
WIN_HEIGHT = 352 + 256 - 64
WIN_SIZE = f"{WIN_WIDTH}x{WIN_HEIGHT}"
WIN_TITLE = "PixelLightCookieGenerator"

PATH_RESOURCES = "resources"
PATH_ICON = f"{PATH_RESOURCES}/icon.png"
PATH_LOGO = f"{PATH_RESOURCES}/logo-full.png"

FORMAT = "RGBA"
MAX_SIZE = 2048
MAX_PREVIEW_SCALE = 16
MAX_PREVIEW_PADDING = 2048
DEFAULT_WIDTH = 64
DEFAULT_HEIGHT = 64
DEFAULT_RADIUS = 24
DEFAULT_OFFSET_X = 0
DEFAULT_OFFSET_Y = 0
DEFAULT_BRIGHTNESS = 255
DEFAULT_COLOR = (255, 255, 255)
DEFAULT_BG = 255
DEFAULT_FALLOFF_START = 4
DEFAULT_FALLOFF_POWER = 16
DEFAULT_FALLOFF_SPREAD = 4
DEFAULT_PREVIEW_SCALE = 2
DEFAULT_PREVIEW_PADDING = 64


UI_FONT = "MS Gothic"

CLR_BG = "#373737"

TXT_GREETING = f"PIXEL LIGHT COOKIE GENERATOR {VERSION}"
TXT_GITHUB = "github.com/mkwozniak/PixelLightCookieGenerator"
